version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5001

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: ${PG_HOST}
      DB_PORT: ${PG_PORT}
      DB_USER: ${PG_USER}
      DB_PASS: ${PG_PASS}
      DB_NAME: ${PG_DB}
      JWT_SECRET: ${JWT_SECRET}
  database:
    image: postgres:15
    container_name: postgresDatabase
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
      JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -h localhost -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  frontend_node_modules:
  backend_node_modules:
