# Use the latest Node 22 official image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if exists)
COPY package*.json ./

# Install backend dependencies
RUN npm install

# Copy all source code to container
COPY . .

# Expose the backend port
EXPOSE 5001

# Start your backend app (remove nodemon if production stage)
CMD ["npm", "run", "dev"]
